<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Forge.Engine\Forge.Engine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Data\production_chains.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Forge.Engine.Tests" />
    <InternalsVisibleTo Include="Forge.Game.Tests" />
  </ItemGroup>
</Project>
